config/routes.rb
# frozen_string_literal: true

PafsCore::Engine.routes.draw do
  resources :bootstraps do
    collection do
      post :funding
      get :spreadsheet
    end
  end

  namespace :projects do
    resources :downloads, only: :index
  end

  resources :archives, only: :index

  resources :projects do
    collection do
      get :pipeline
    end
    member do
      resources :downloads, only: :index do
        collection do
          get :proposal
          get :benefit_area
          get :funding_calculator
          get :moderation
          get :delete_funding_calculator
          get :delete_benefit_area
        end
      end
      get :archive
      get :submit
      get :complete
      get :unlock
      get :confirm
    end
  end

  resources :multi_downloads, only: :index do
    collection do
      get :generate
      get :proposals
      get :benefit_areas
      get :funding_calculators
      get :moderations
    end
  end

  resources :areas, only: %i[index show] do
    member do
      get :set_user
    end
  end

  get "bootstrap/:id/:step" => "bootstraps#step", as: :bootstrap_step
  patch "bootstrap/:id/:step" => "bootstraps#save", as: :save_bootstrap_step
  get "projects/:id/:step" => "projects#step", as: :project_step
  patch "projects/:id/:step" => "projects#save", as: :save_project_step

  post "confirmation" => "confirmation#receipt", as: :confirm_receipt
  match "(errors)/:status", to: "errors#show", via: :all, constraints: { status: /\d{3}/ }

  get "/cookies", to: "pages#cookies"
end

app/views/pafs_core/projects/steps/location/_location.html.erb
<h1 class="heading-large"><%= t('.heading') %></h1>
<p><%= location_search_results_for(results, params[:q], t(".result"), t(".description")) %> <%= %></p>
<ul>
  <%= pafs_form_for @project, url: save_project_step_path(id: @project.to_param, step: @project.step) do |f| %>
    <div class="form-group">
      <% result = results.first %>
      <li>
        <%= f.radio_button :project_location, result, label: search_result_label(params[:address], result) %>
      </li>
    </div>
    <div class="form-group">
      <%= link_to t(".location_not_listed"), project_step_path(id: @project, step: @project.step, params: { search: "true"}) %>
    </div>
    <div class="form-group">
      <%= f.submit t("save_and_continue_label"), class: "button" %>
    </div>
  <% end %>
</ul>

app/views/pafs_core/projects/steps/location/_map.html.erb
<% map_centre = results.first %>
<% content_for :page_title, make_page_title(t("location_confirmation", scope: "page_titles")) %>
<div class="grid-row">
  <div class="column-three-thirds">
    <h1 class="heading-large"><%= t('.heading') %></h1>
    <p><%= t('.description') %></p>
    <div id="map"
      class="location"
      data-eastings=<%= map_centre[:eastings] %>
      data-northings=<%= map_centre[:northings] %>
      data-zoomlevel=<%= @project.project_location_zoom_level %>
      data-polygons= <%= JSON.parse(@project.benefit_area).to_json %>
      data-marker=<%= @project.marker.to_json %>>
    </div>
  </div>
</div>
<%= form_for @project, url: save_project_step_path(id: @project.to_param, step: @project.step) do |f| %>
  <div class="form-group">
    <%= link_to t(".find_another_location"), project_step_path(id: @project, step: @project.step, params: { search: "true"}) %>
    <%= f.hidden_field :project_location %>
    <%= f.hidden_field :project_location_zoom_level %>
  </div>

  <%= f.submit t("confirm_and_continue_label"), class: 'button', id: 'locationSaveButton' %>
<% end %>

app/views/pafs_core/projects/steps/location/_results.html.erb
<h1 class="heading-large"><%= t('.heading') %></h1>
<p><%= location_search_results_for(results, params[:q], t(".result"), t(".description")) %></p>
<%= pafs_form_for '', method: :get do |f| %>
  <fieldset>
    <legend class="visually-hidden"><%= t('.heading') %></legend>
    <div class="form-group">
      <% results.each do |result| %>
        <%= f.radio_button :q, "#{result[:eastings].to_i}, #{result[:northings].to_i}".html_safe, label: result[:address].html_safe %>
      <% end %>
      <div class="hidden">
        <%= f.radio_button :q, params[:q], label: params[:q].html_safe, checked: true %>
      </div>
    </div>
  </fieldset>
  <div class="form-group">
    <%= link_to t(".location_not_listed"), project_step_path(id: @project, step: @project.step, params: { search: "true"}) %>
  </div>
  <div class="form-group">
    <%= f.submit t("confirm_and_continue_label"), class: "button" %>
  </div>
<% end %>

app/views/pafs_core/projects/steps/location/_search.html.erb
<%= pafs_form_for @project, url: project_step_path(id: @project.to_param, step: @project.step), method: :get do |f| %>
  <div class="form-group">
    <h1 class="heading-large"><%= t('.heading') %></h1>
    <p class="form-hint"><%= t('.example_text') %></p>
    <%= f.form_group(:base) do %>
      <%= f.error_message(:base) %>
      <%= text_field_tag :q, params[:q], label: nil , class: "form-control"%>
    <% end %>
  </div>
  <div class="form-group">
    <%= submit_tag t('.search_label'), class: "button" %>
  </div>
<% end %>