config/routes.rb
# frozen_string_literal: true

PafsCore::Engine.routes.draw do
  resources :bootstraps do
    collection do
      post :funding
      get :spreadsheet
    end
  end

  namespace :projects do
    resources :downloads, only: :index
  end

  resources :archives, only: :index

  resources :projects do
    collection do
      get :pipeline
    end
    member do
      resources :downloads, only: :index do
        collection do
          get :proposal
          get :benefit_area
          get :funding_calculator
          get :moderation
          get :delete_funding_calculator
          get :delete_benefit_area
        end
      end
      get :archive
      get :submit
      get :complete
      get :unlock
      get :confirm
    end
  end

  resources :multi_downloads, only: :index do
    collection do
      get :generate
      get :proposals
      get :benefit_areas
      get :funding_calculators
      get :moderations
    end
  end

  resources :areas, only: %i[index show] do
    member do
      get :set_user
    end
  end

  get "bootstrap/:id/:step" => "bootstraps#step", as: :bootstrap_step
  patch "bootstrap/:id/:step" => "bootstraps#save", as: :save_bootstrap_step
  get "projects/:id/:step" => "projects#step", as: :project_step
  patch "projects/:id/:step" => "projects#save", as: :save_project_step

  post "confirmation" => "confirmation#receipt", as: :confirm_receipt
  match "(errors)/:status", to: "errors#show", via: :all, constraints: { status: /\d{3}/ }

  get "/cookies", to: "pages#cookies"
end

app/views/summary/_approach.html.erb
<article class="summary-item" aria-labelledby="approach">
  <% if project.approach.present? %>
    <div class="summary-item-content">
      <h2 class="heading-medium" role="heading" id="approach"><%= project.summary_label(:approach_title) %></h2>
      <div class="grid-row">
        <div class="column-three-quarters">
          <%= simple_format project.approach %>
        </div>
        <div class="column-one-quarter">
          <% if project.draft? %>
            <% if can_edit_project_sections?(project) -%>
              <div class="change-link">
                <%= link_to pafs_core.project_step_path(id: project.to_param, step: :approach) do -%>
                  Change<span class="visually-hidden"> <%= project.summary_label(:approach_title).downcase %></span>
                <% end -%>
              </div>
            <% end -%>
          <% end %>
        </div>
      </div>
    </div>
  <% else %>
    <div class="add-row">
      <div class="grid-row">
        <div class="column-three-quarters">
          <h2 class="heading-medium" role="heading" id="approach"><%= project.summary_label(:approach_title) %></h2>
        </div>
        <div class="column-one-quarter">
          <% unless project.archived? %>
            <% if can_edit_project_sections?(project) -%>
              <div class="add-link">
                <%= link_to pafs_core.project_step_path(id: project.to_param, step: :approach) do -%>
                  Add<span class="visually-hidden"> <%= project.summary_label(:approach_title).downcase %></span>
                <% end -%>
              </div>
            <% end -%>
          <% end -%>
        </div>
      </div>
    </div>
  <% end %>
</article>

app/views/summary/_carbon.html.erb
<article class="summary-item" aria-labelledby="carbon">
  <% if project.carbon_started? %>
    <div class="summary-item-content">
      <h2 class="heading-medium" role="heading" id="carbon">
        <%= project.summary_label(:carbon_title) %>
      </h2>
      <div class="grid-row">
        <div class="column-three-quarters">
          <table class="full-table">
            <thead>
              <tr>
                <th class="visuallyhidden">Category</th>
                <th class="visuallyhidden">Carbon amount in metric tonnes</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= project.summary_label(:carbon_cost_build) %></td>
                <td class="align-right"><%= number_to_human(project.carbon_cost_build, significant: false, units: { unit: 'tonnes' }) %></td>
              </tr>
              <tr>
                <td><%= project.summary_label(:carbon_cost_operation) %></td>
                <td class="align-right"><%= number_to_human(project.carbon_cost_operation, significant: false, units: { unit: 'tonnes' }) %></td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="column-one-quarter">
          <% if project.draft? %>
            <% if can_edit_project_sections?(project) -%>
              <div class="change-link">
                <%= link_to pafs_core.project_step_path(id: project.to_param, step: :carbon_cost_build) do -%>
                  Change<span class="visually-hidden"> the <%= project.summary_label(:carbon).downcase %></span>
                <% end -%>
              </div>
            <% end -%>
          <% end -%>
        </div>
      </div>
    </div>
  <% else %>
    <div class="add-row">
      <div class="grid-row">
        <div class="column-three-quarters">
          <h2 class="heading-medium" role="heading" id="carbon">
            <%= project.summary_label(:carbon_title) %>
          </h2>
        </div>
        <div class="column-one-quarter">
          <% unless project.archived? %>
            <% if can_edit_project_sections?(project) -%>
              <div class="add-link">
                <%= link_to pafs_core.project_step_path(id: project.to_param, step: :carbon_cost_build) do -%>
                  Add<span class="visually-hidden"> <%= project.summary_label(:carbon_title).downcase %></span>
                <% end -%>
              </div>
            <% end -%>
          <% end -%>
        </div>
      </div>
    </div>
  <% end %>
</article>

app/views/summary/_confidence.html.erb
<article class="summary-item" aria-labelledby="confidence">
  <% if project.confidence_started? %>
    <div class="summary-item-content">
      <h2 class="heading-medium" role="heading" id="confidence">
        <%= project.summary_label(:confidence_title) %>
      </h2>
      <div class="grid-row">
        <div class="column-three-quarters">
          <table class="full-table">
            <thead>
              <tr>
                <th class="visuallyhidden">Assessment</th>
                <th class="visuallyhidden">Confidence</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= project.summary_label(:confidence_homes_better_protected) %></td>
                <td class="align-right"><%= t(:label, scope: ['pafs_core', 'confidence', 'homes_better_protected', project.confidence_homes_better_protected]) %></td>
              </tr>
              <tr>
                <td><%= project.summary_label(:confidence_homes_by_gateway_four) %></td>
                <td class="align-right"><%= t(:label, scope: ['pafs_core', 'confidence', 'homes_by_gateway_four', project.confidence_homes_by_gateway_four]) %></td>
              </tr>
              <tr>
                <td><%= project.summary_label(:confidence_secured_partnership_funding) %></td>
                <td class="align-right"><%= t(:label, scope: ['pafs_core', 'confidence', 'secured_partnership_funding', project.confidence_secured_partnership_funding]) %></td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="column-one-quarter">
          <% if project.draft? %>
            <% if can_edit_project_sections?(project) -%>
              <div class="change-link">
                <%= link_to pafs_core.project_step_path(id: project.to_param, step: :confidence_homes_better_protected) do -%>
                  Change<span class="visually-hidden"> the <%= project.summary_label(:confidence).downcase %></span>
                <% end -%>
              </div>
            <% end -%>
          <% end -%>
        </div>
      </div>
    </div>
  <% else %>
    <div class="add-row">
      <div class="grid-row">
        <div class="column-three-quarters">
          <h2 class="heading-medium" role="heading" id="confidence">
            <%= project.summary_label(:confidence_title) %>
          </h2>
        </div>
        <div class="column-one-quarter">
          <% unless project.archived? %>
            <% if can_edit_project_sections?(project) -%>
              <div class="add-link">
                <%= link_to pafs_core.project_step_path(id: project.to_param, step: :confidence_homes_better_protected) do -%>
                  Add<span class="visually-hidden"> <%= project.summary_label(:confidence_title).downcase %></span>
                <% end -%>
              </div>
            <% end -%>
          <% end -%>
        </div>
      </div>
    </div>
  <% end %>
</article>

app/views/summary/_data_notice.html.erb
<details role="group">
  <summary role="button" aria-controls="data-notice">
    <span class="summary">Standard data notice</span>
  </summary>
  <div class="panel panel-indent panel-border-narrow" id="data-notice">
    <h2 class="heading-small">How we will use your personal information?</h2>
    <p class="list-intro">
      The Environment Agency will process the information you provide so that
      we can:
    </p>
    <ul class="list-bullet spaced-list">
      <li>review your proposal</li>
      <li>prioritise your proposal</li>
      <li>determine eligibility for indicative grant-in-aid funding</li>
    </ul>
    <h2 class="heading-small">We may also process or release the information to:</h2>
    <ul class="list-bullet spaced-list">
      <li>offer you documents or services relating to environmental matters</li>
      <li>consult the public, public organisations and other organisations (for example, the Health and Safety Executive) on environmental issues</li>
      <li>carry out research and development work on environmental issues</li>
      <li>assess whether customers are satisfied with our service, and improve our service</li>
      <li>respond to information requests under the Freedom of Information Act 2000 and the Environmental Information Regulations 2004 (if the Data Protection Act allows)</li>
    </ul>
    <p>
      We may pass the information on to our agents or representatives to do
      these things for us.
    </p>
  </div>
</details>

app/views/summary/_earliest_start.html.erb
<article class="summary-item" aria-labelledby="earliest-start">
  <% if project.earliest_start_started? %>
    <div class="summary-item-content">
      <h2 class="heading-medium" role="heading" id="earliest-start">Earliest start</h2>
      <div class="grid-row">
        <div class="column-two-thirds">
          <% if project.could_start_early? %>
            <% if project.earliest_start_month.nil? %>
              <p><em>The earliest date the project could start has not been provided</em><p>
                <% else %>
                  <p>The earliest date the project could start without impacting deliverability or outcomes is <%= project.earliest_start_date %></p>
                <% end %>
              <% else %>
                <p>The project cannot start earlier without impacting deliverability or outcomes.</p>
              <% end %>
        </div>
        <div class="column-one-third">
          <% if project.draft? %>
            <% if can_edit_project_sections?(project) -%>
              <div class="change-link">
                <%= link_to pafs_core.project_step_path(id: project.to_param, step: :earliest_start) do -%>
                  Change<span class="visually-hidden"> whether the project could start earlier without impacting deliverability or outcomes</span>
                <% end -%>
              </div>
            <% end -%>
          <% end -%>
        </div>
      </div>
    </div>
  <% else %>
    <div class="add-row">
      <div class="grid-row">
        <div class="column-three-quarters">
          <h2 class="heading-medium" role="heading" id="earliest-start">Earliest start</h2>
        </div>
        <div class="column-one-quarter">
          <% unless project.archived? %>
            <% if can_edit_project_sections?(project) -%>
              <div class="add-link">
                <%= link_to pafs_core.project_step_path(id: project.to_param, step: :earliest_start) do -%>
                  Add<span class="visually-hidden"> whether the project could start earlier without impacting deliverability or outcomes</span>
                <% end -%>
              </div>
            <% end -%>
          <% end -%>
        </div>
      </div>
    </div>
  <% end %>
</article>

app/views/summary/_financial_year.html.erb
<article class="summary-item" aria-labelledby="financial-year">
  <div class="summary-item-content">
    <h2 class="heading-medium" role="heading" id="financial-year">Last financial year the project will spend funds</h2>
    <div class="grid-row">
      <div class="column-two-thirds">
        <p><%= formatted_financial_month_and_year project.project_end_financial_year %></p>
      </div>
      <div class="column-one-third">
        <% if project.draft? %>
          <% if can_edit_project_sections?(project) -%>
            <div class="change-link">
              <%= link_to pafs_core.project_step_path(id: project.to_param, step: :financial_year) do -%>
                Change<span class="visually-hidden"> the last financial year the project will spend funds</span>
              <% end -%>
            </div>
          <% end -%>
        <% end -%>
      </div>
    </div>
  </div>
</article>

app/views/summary/_flood_protection_outcomes_detail.html.erb
<div class="step-container">
  <div>
    <div>
      <h2 class="heading-medium" role="heading" id="flood_protection_outcomes_detail"><%= project.summary_label(:flood_protection_outcomes_detail_heading) %></h2>
      <p><%= project.summary_label(:flood_protection_outcomes_detail_lede) %></p>
      <div class="step-form">
        <div class="scroll-horz">
          <table>
            <thead>
            <tr>
              <th class="financial-year-column"><%= project.summary_label(:financial_year_label) %></th>
              <th class="risk-summary-heading"><%= project.summary_label(:households_at_reduced_risk_label) %></th>
              <th class="risk-summary-heading"><%= project.summary_label(:households_moved_from_very_significant_and_significant_to_moderate_or_low_label) %></th>
              <th class="risk-summary-heading"><%= project.summary_label(:households_protected_from_loss_in_20_percent_most_deprived_label) %></th>
            </tr>
            <tr>
              <td></td>
              <th class="risk-summary-subheading">A</th>
              <th class="risk-summary-subheading">B</th>
              <th class="risk-summary-subheading">C</th>
            </tr>
            </thead>
            <tbody>
            <% project.current_flood_protection_outcomes.each do |fo| %>
                <tr>
                  <td class="financial_year">
                    <%= formatted_financial_year(fo.financial_year) %>
                  </td>
                  <td class="<%= funding_table_cell(fo.financial_year, fo.households_at_reduced_risk) %>">
                    <%= number_with_delimiter fo.households_at_reduced_risk %>
                  </td>
                  <td class="<%= funding_table_cell(fo.financial_year, fo.moved_from_very_significant_and_significant_to_moderate_or_low) %> significant-to-low-risk">
                    <%= number_with_delimiter fo.moved_from_very_significant_and_significant_to_moderate_or_low %>

                  </td>
                  <td class="<%= funding_table_cell(fo.financial_year, fo.households_protected_from_loss_in_20_percent_most_deprived) %>">
                    <%= number_with_delimiter fo.households_protected_from_loss_in_20_percent_most_deprived %>

                  </td>
                </tr>
            <% end %>
            </tbody>
            <tfoot>
            <tr>
              <td><%= project.summary_label(:total_label) %></td>
              <td class="numeric households-at-reduced-risk-total"><%= number_with_delimiter project.total_households_flood_protected_by_category(:households_at_reduced_risk)%></td>
              <td class="numeric moved-from-very-significant-and-significant-to-moderate-or-low-total"><%= number_with_delimiter project.total_households_flood_protected_by_category(:moved_from_very_significant_and_significant_to_moderate_or_low)%></td>
              <td class="numeric households-protected-from-loss-in-20-percent-most-deprived-total"><%= number_with_delimiter project.total_households_flood_protected_by_category(:households_protected_from_loss_in_20_percent_most_deprived)%></td>
            </tr>
            </tfoot>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/summary/_funding_calculator.html.erb
<article class="summary-item" aria-labelledby="funding-calculator">
  <% if project.funding_calculator_uploaded? %>
    <div class="summary-item-content">
      <h2 class="heading-medium" role="heading" id="funding-calculator"><%= project.summary_label(:funding_calculator_title) %></h2>
      <div class="grid-row">
        <div class="column-three-quarters">
          <div class="attachment">
            <div class="attachment-thumb">
              <%= link_to funding_calculator_downloads_path(project.to_param),
                class: "thumbnail", aria: { hidden: "true" } do -%>
                <%= image_tag "pafs_core/pub-cover-spreadsheet.png", alt: "Download file #{project.funding_calculator_file_name}" %>
              <% end %>
            </div>
            <div class="attachment-details">
              <h3 class="title">
                <%= link_to funding_calculator_downloads_path(project.to_param),
                  aria: { described_by: "funding-calculator" } do -%>
                  <span class="visually-hidden">Download your funding calculator </span>
                  <%= project.funding_calculator_file_name %>
                <% end %>
              </h3>
              <dl class="metadata">
                <dt>Size</dt>
                <dd><%= number_to_human_size(project.funding_calculator_file_size) -%></dd>
                <dt>Uploaded</dt>
                <dd><%= format_date project.funding_calculator_updated_at %></dd>
              </dl>
            </div>
          </div>
        </div>
        <div class="column-one-quarter">
          <% if project.draft? %>
            <% if can_edit_project_sections?(project) -%>
              <div class="change-link">
                <%= link_to pafs_core.project_step_path(id: project.to_param, step: :funding_calculator_summary) do -%>
                  Change<span class="visually-hidden"> the funding calculator file</span>
                <% end -%>
              </div>
            <% end -%>
          <% end -%>
        </div>
      </div>
    </div>
  <% else %>
    <div class="add-row">
      <div class="grid-row">
        <div class="column-three-quarters">
          <h2 class="heading-medium" role="heading" id="funding-calculator"><%= project.summary_label(:funding_calculator_title) %></h2>
        </div>
        <div class="column-one-quarter">
          <% unless project.archived? %>
            <% if can_edit_project_sections?(project) -%>
              <div class="add-link">
                <%= link_to pafs_core.project_step_path(id: project.to_param, step: :funding_calculator) do -%>
                  Add<span class="visually-hidden"> <%= project.summary_label(:funding_calculator_title).downcase %></span>
                <% end -%>
              </div>
            <% end -%>
          <% end -%>
        </div>
      </div>
    </div>
  <% end %>
</article>

app/views/summary/_funding_sources.html.erb
<article class="summary-item" aria-labelledby="funding-sources">
  <% if project.funding_sources_started? %>
      <div class="summary-item-content">
        <h2 class="heading-medium" role="heading" id="funding-sources">Funding sources and spending</h2>
        <div class="grid-row">
          <div class="column-three-quarters">
            <table class="full-table">
              <thead>
              <tr>
                <th>Funding Source</th>
                <th class="align-right">Total Estimated Spend</th>
              </tr>
              </thead>
              <tbody>
              <% project.funding.each do |f| %>
                  <tr>
                    <td><%= f[:name] %></td>
                    <td class="align-right">£<%= number_with_delimiter f[:value] %></td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>
          <div class="column-one-quarter">
            <% if project.draft? %>
              <% if can_edit_project_sections?(project) -%>
                <div class="change-link">
                  <%= link_to pafs_core.project_step_path(id: project.to_param, step: :funding_sources) do -%>
                      Change<span class="visually-hidden"> the sources of funding</span>
                  <% end -%>
                </div>
              <% end -%>
            <% end -%>
          </div>
        </div>
        <% if !project.draft? %>
            <div>
              <div>
                <details>
                  <summary class="half-indent-with-top-margin" role="button" aria-controls="show_funding_sources_and_spending_detail">
                    <span class="summary"> View funding sources and spending detail </span>
                  </summary>
                  <div id="show_funding_sources_and_spending_detail" class="panel panel-indent panel-border-narrow">
                    <%= render partial: "summary/funding_sources_and_spending_detail", locals: {project: @project} %>
                  </div>
                </details>
              </div>
            </div>
        <% end %>
      </div>
  <% else %>
      <div class="add-row">
        <div class="grid-row">
          <div class="column-three-quarters">
            <h2 class="heading-medium" role="heading" id="funding-sources">Funding sources and spending</h2>
          </div>
          <div class="column-one-quarter">
            <% unless project.archived? %>
              <% if can_edit_project_sections?(project) -%>
                <div class="add-link">
                  <%= link_to pafs_core.project_step_path(id: project.to_param, step: :funding_sources) do -%>
                    Add<span class="visually-hidden"> the funding sources and spending details</span>
                  <% end -%>
                </div>
              <% end -%>
            <% end -%>
          </div>
        </div>
      </div>
  <% end %>
</article>

app/views/summary/_funding_values.html.erb
<article class="summary-item" aria-labelledby="funding-values">
  <% if project.funding_values_started? %>
    <h2 class="heading-medium" role="heading" id="funding-values">Funding values</h2>
    <div class="grid-row">
      <div class="column-two-thirds">
        <ul class="summary-list underlined-items">
          <% project.funding.each do |f| %>
            <li>
              <span class="half-width"><%= f[:name] %></span>
              <span class="pull-right">£<%= number_with_delimiter f[:value] %></span>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="column-one-third">
        <% if project.draft? %>
          <% if can_edit_project_sections?(project) -%>
            <div class="change-link">
              <%= link_to pafs_core.project_step_path(id: project.to_param, step: :funding_values) do -%>
                Change<span class="visually-hidden"> the funding values</span>
              <% end -%>
            </div>
          <% end -%>
        <% end -%>
      </div>
    </div>
  <% else %>
    <div class="add-row">
      <div class="grid-row">
        <div class="column-three-quarters">
          <h2 class="heading-medium" role="heading" id="funding-values">Funding values</h2>
        </div>
        <div class="column-one-quarter">
          <% unless project.archived? %>
            <% if can_edit_project_sections?(project) -%>
              <div class="add-link">
                <%= link_to pafs_core.project_step_path(id: project.to_param, step: :funding_values) do -%>
                  Add<span class="visually-hidden"> the funding values</span>
                <% end -%>
              </div>
            <% end -%>
          <% end -%>
        </div>
      </div>
    </div>
  <% end %>
</article>

app/views/summary/_key_dates.html.erb
<article class="summary-item" aria-labelledby="key-dates">
  <% if project.key_dates_started? %>
    <div class="summary-item-content">
      <h2 class="heading-medium" role="heading" id="key-dates">Important dates</h2>
      <div class="grid-row">
        <div class="column-three-quarters">
          <table class="full-table">
            <thead>
              <tr>
                <th class="visuallyhidden">Important date</th>
                <th class="visuallyhidden">Date</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= t(".start_outline_business_case_label") %></td>
                <td class="align-right"><%= project.start_outline_business_case_date %></td>
              </tr>
              <tr>
                <td><%= t(".award_contract_label") %></td>
                <td class="align-right"><%= project.award_contract_date %></td>
              </tr>
              <tr>
                <td><%= t(".start_construction_label") %></td>
                <td class="align-right"><%= project.start_construction_date %></td>
              </tr>
              <tr>
                <td><%= t(".ready_for_service_label") %></td>
                <td class="align-right"><%= project.ready_for_service_date %></td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="column-one-quarter">
          <% if project.draft? %>
            <% if can_edit_project_sections?(project) -%>
              <div class="change-link">
                <%= link_to pafs_core.project_step_path(id: project.to_param, step: :start_outline_business_case_date) do -%>
                  Change<span class="visually-hidden"> the <%= t(".start_outline_business_case_label").downcase %></span>
                <% end -%>
              </div>
            <% end -%>
          <% end -%>
        </div>
      </div>
    </div>
  <% else %>
    <div class="add-row">
      <div class="grid-row">
        <div class="column-three-quarters">
          <h2 class="heading-medium" role="heading" id="key-dates">Important dates</h2>
        </div>
        <div class="column-one-quarter">
          <% unless project.archived? %>
            <% if can_edit_project_sections?(project) -%>
              <div class="add-link">
                <%= link_to pafs_core.project_step_path(id: project.to_param, step: :start_outline_business_case_date) do -%>
                  Add<span class="visually-hidden"> the important dates</span>
                <% end -%>
              </div>
            <% end -%>
          <% end -%>
        </div>
      </div>
    </div>
  <% end %>
</article>

app/views/summary/_location.html.erb
<article class="summary-item" aria-labelledby="location">
  <% if project.location_set? %>
    <div class="summary-item-content">
      <h2 class="heading-medium" role="heading" id="location"><%= project.summary_label(:location_title) %></h2>
      <div class="grid-row">
        <div class="column-one-half">
          <h3 class="column-heading-small">National Grid Reference</h3>
        </div>
      </div>
      <div class="grid-row">
        <div class="column-one-quarter aslign-right">
          <%= project.grid_reference %>
        </div>
        <div class="column-one-half">
          <div class="map-link">
            <%= link_to t("see_this_location_link_label"),
              project.grid_reference_link,
              rel: "external",
              target: "_blank" %>
          </div>
        </div>
        <div class="column-one-quarter align-right">
          <% if project.draft? %>
            <% if can_edit_project_sections?(project) -%>
              <div class="change-link">
                <%= link_to pafs_core.project_step_path(id: project.to_param, step: :location) do -%>
                  Change<span class="visually-hidden"> <%= project.summary_label(:location_title).downcase %></span>
                <% end -%>
              </div>
            <% end -%>
          <% end -%>
        </div>
      </div>
      <% if project.show_location_data? %>
        <div class="grid-row">
          <div class="column-two-thirds">
            <p><strong>Region:</strong> <%= project.region %><br/>
              <strong>County:</strong> <%= project.county %><br/>
              <strong>Constituency:</strong> <%= project.parliamentary_constituency %></p>
          </div>
        </div>
      <% end -%>
      <% if project.benefit_area_file_uploaded? %>
        <div class="grid-row">
          <div class="column-two-thirds">
            <h3 class="column-heading-small">Project benefit area</h3>
            <div class="attachment">
              <div class="attachment-thumb">
                <%= link_to benefit_area_downloads_path(project.to_param),
                  class: "thumbnail", aria: { hidden: "true" } do -%>
                  <%= image_tag "pafs_core/pub-cover-shapefile.png", alt: "Download file #{project.benefit_area_file_name}" %>
                <% end %>
              </div>
              <div class="attachment-details">
                <h3 class="title">
                  <%= link_to benefit_area_downloads_path(project.to_param),
                    aria: { described_by: "location" } do -%>
                    <span class="visually-hidden">Download your benefit area file </span>
                    <%= project.benefit_area_file_name %>
                  <% end %>
                </h3>
                <dl class="metadata">
                  <dt>Size</dt>
                  <dd><%= number_to_human_size(project.benefit_area_file_size) -%></dd>
                  <dt>Uploaded</dt>
                  <dd><%= format_date project.benefit_area_file_updated_at %></dd>
                </dl>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <div class="grid-row">
          <div class="column-two-thirds">
            <h3 class="column-heading-small">Project benefit area</h3>
          </div>
        </div>
        <div class="grid-row">
          <div class="column-two-thirds">
            <div class="footroom">
              <%= project.not_provided %>
            </div>
          </div>
        </div>
      <% end -%>
    </div>
  <% else %>
    <div class="add-row">
      <div class="grid-row">
        <div class="column-three-quarters">
          <h2 class="heading-medium" role="heading" id="location">
            <%= project.summary_label(:location_title) %>
          </h2>
        </div>
        <div class="column-one-quarter">
          <% unless project.archived? %>
            <% if can_edit_project_sections?(project) -%>
              <div class="add-link">
                <%= link_to pafs_core.project_step_path(id: project.to_param, step: :location) do -%>
                  Add<span class="visually-hidden"> <%= project.summary_label(:location_title).downcase %></span>
                <% end -%>
              </div>
            <% end -%>
          <% end -%>
        </div>
      </div>
    </div>
  <% end %>
</article>