config/routes.rb
# frozen_string_literal: true

PafsCore::Engine.routes.draw do
  resources :bootstraps do
    collection do
      post :funding
      get :spreadsheet
    end
  end

  namespace :projects do
    resources :downloads, only: :index
  end

  resources :archives, only: :index

  resources :projects do
    collection do
      get :pipeline
    end
    member do
      resources :downloads, only: :index do
        collection do
          get :proposal
          get :benefit_area
          get :funding_calculator
          get :moderation
          get :delete_funding_calculator
          get :delete_benefit_area
        end
      end
      get :archive
      get :submit
      get :complete
      get :unlock
      get :confirm
    end
  end

  resources :multi_downloads, only: :index do
    collection do
      get :generate
      get :proposals
      get :benefit_areas
      get :funding_calculators
      get :moderations
    end
  end

  resources :areas, only: %i[index show] do
    member do
      get :set_user
    end
  end

  get "bootstrap/:id/:step" => "bootstraps#step", as: :bootstrap_step
  patch "bootstrap/:id/:step" => "bootstraps#save", as: :save_bootstrap_step
  get "projects/:id/:step" => "projects#step", as: :project_step
  patch "projects/:id/:step" => "projects#save", as: :save_project_step

  post "confirmation" => "confirmation#receipt", as: :confirm_receipt
  match "(errors)/:status", to: "errors#show", via: :all, constraints: { status: /\d{3}/ }

  get "/cookies", to: "pages#cookies"
end

app/models/pafs_core/account_request.rb
# Play nice with Ruby 3 (and rubocop)
# frozen_string_literal: true

module PafsCore
  class AccountRequest < ApplicationRecord
    validates :first_name, presence: { message: "^Tell us your first name." }
    validates :last_name, presence: { message: "^Tell us your last name." }
    validates :email, presence: { message: "^Tell us your work email address." }
    validates :email, format: {
      with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,
      on: :create,
      message: "^Enter a valid work email address."
    }, allow_blank: true
    validates :email, uniqueness: true
    validates :organisation, presence: { message: "^Tell us the organisation you work for." }
    validates :job_title, presence: { message: "^Tell us your job title." }
    validates :telephone_number, presence: { message: "^Tell us your telephone number." }
    # validates :telephone_number, format: {
    #   with: /\A(?x)(?:(?:\(?(?:0(?:0|11)\)?[\s-]?\(?|\+)44\)?[\s-]?(?:\(?0\)?[\s-]?)?)|
    #     (?:\(?0))(?:(?:\d{5}\)?[\s-]?\d{4,5})|(?:\d{4}\)?[\s-]?(?:\d{5}|\d{3}[\s-]?\d{3}))|
    #     (?:\d{3}\)?[\s-]?\d{3}[\s-]?\d{3,4})|(?:\d{2}\)?[\s-]?\d{4}[\s-]?\d{4}))
    #     (?:[\s-]?(?:x|ext\.?|\#)\d{3,4})?\z/,
    #   on: :create,
    #   message: "^Enter a valid telephone number"
    # }, allow_blank: true
    before_validation :downcase_email
    before_create :generate_slug

    def self.expired
      where(arel_table[:updated_at].lt(30.days.ago))
    end

    def to_param
      slug
    end

    def full_name
      "#{first_name} #{last_name}" unless first_name.nil? || last_name.nil?
    end

    private

    def generate_slug
      self.slug = email.parameterize
    end

    def downcase_email
      email&.downcase!
    end
  end
end

app/models/pafs_core/area.rb
# frozen_string_literal: true

module PafsCore
  class Area < ApplicationRecord
    AREA_TYPES = [
      COUNTRY_AREA = "Country",
      EA_AREA      = "EA Area",
      PSO_AREA     = "PSO Area",
      RMA_AREA     = "RMA"
    ].freeze

    validates_presence_of :name, :area_type
    validates_uniqueness_of :name
    validate :parentage
    validates_inclusion_of :area_type, in: AREA_TYPES
    validates :sub_type, presence: true, if: :rma?

    belongs_to :parent, class_name: "Area", optional: true
    has_many :children, class_name: "Area", foreign_key: "parent_id"
    has_many :area_projects
    has_many :projects, through: :area_projects
    has_one :area_download, inverse_of: :area

    scope :top_level, -> { where(parent_id: nil) }

    def self.country
      find_by(area_type: AREA_TYPES[0])
    end

    def self.ea_areas
      where(area_type: AREA_TYPES[1])
    end

    def self.pso_areas
      where(area_type: AREA_TYPES[2])
    end

    def self.rma_areas
      where(area_type: AREA_TYPES[3])
    end

    def country?
      area_type == AREA_TYPES[0]
    end

    def ea_area?
      area_type == AREA_TYPES[1]
    end

    def pso_area?
      area_type == AREA_TYPES[2]
    end

    def rma?
      area_type == AREA_TYPES[3]
    end

    def ea_parent
      return self if ea_area?

      if ea_area?
        self
      elsif pso_area?
        parent
      elsif rma?
        parent.parent
      else
        raise "Cannot find ea parent for #{name}"
      end
    end

    def self.name_matches(q)
      where(arel_table[:name].matches(q))
    end

    def parentage
      if !country? && parent_id.blank?
        errors.add(:parent_id, "can't be blank")
      elsif country? && parent_id.present?
        errors.add(:parent_id, "must be blank")
      end
    end
  end
end

app/models/pafs_core/area_download.rb
# Play nice with Ruby 3 (and rubocop)
# frozen_string_literal: true

require "bstard"

module PafsCore
  class AreaDownload < ApplicationRecord
    belongs_to :area, inverse_of: :area_download, optional: true
    belongs_to :user, inverse_of: :area_downloads, optional: true

    # rubocop:disable Style/HashSyntax
    def documentation_state
      machine = Bstard.define do |fsm|
        fsm.initial current_status
        fsm.event :generate, :empty => :generating, :ready => :generating, :failed => :generating
        fsm.event :complete, :generating => :ready
        fsm.event :error, :generating => :failed
        fsm.when :any do |_event, _prev_state, new_state|
          self.status = new_state
          save!
        end
      end
    end
    # rubocop:enable Style/HashSyntax

    def current_status
      status || :empty
    end
  end
end

app/models/pafs_core/area_project.rb
# Play nice with Ruby 3 (and rubocop)
# frozen_string_literal: true

module PafsCore
  class AreaProject < ApplicationRecord
    belongs_to :project
    belongs_to :area

    scope :ownerships, -> { where(owner: true) }
  end
end

app/models/pafs_core/asite_file.rb
# frozen_string_literal: true

module PafsCore
  class AsiteFile < ApplicationRecord
    belongs_to :asite_submission, inverse_of: :asite_files
    validates :filename, :checksum, presence: true
  end
end

app/models/pafs_core/asite_submission.rb
# frozen_string_literal: true

module PafsCore
  class AsiteSubmission < ApplicationRecord
    belongs_to :project, inverse_of: :asite_submissions
    has_many :asite_files, inverse_of: :asite_submission
    validates :email_sent_at, presence: true
    validates :status, presence: true

    def self.sent
      where(status: "sent")
    end

    def self.sent_or_unsuccessful
      t = arel_table
      where(t[:status].eq("sent").or(t[:status].eq("failed")))
    end

    # rubocop:disable Style/HashSyntax
    def submission_state
      machine = Bstard.define do |fsm|
        fsm.initial status
        fsm.event :deliver, :created => :sent
        fsm.event :confirm, :sent => :succeeded
        fsm.event :reject, :sent => :failed
        fsm.when :any do |_event, _prev, new_state|
          self.status = new_state
          save!
        end
      end
    end
    # rubocop:enable Style/HashSyntax
  end
end

app/models/pafs_core/bootstrap.rb
# Play nice with Ruby 3 (and rubocop)
# frozen_string_literal: true

module PafsCore
  class Bootstrap < ApplicationRecord
    validates :slug, presence: true, uniqueness: true
    belongs_to :creator, class_name: "User", optional: true

    before_validation :set_slug, on: :create

    def reference_number
      slug
    end

    def to_param
      slug
    end

    private

    def set_slug
      self.slug = SecureRandom.urlsafe_base64
    end
  end
end

app/models/pafs_core/coastal_erosion_protection_outcome.rb
# frozen_string_literal: true

module PafsCore
  class CoastalErosionProtectionOutcome < ApplicationRecord
    belongs_to :project

    validates_numericality_of :households_at_reduced_risk,
                              :households_protected_from_loss_in_next_20_years,
                              :households_protected_from_loss_in_20_percent_most_deprived,
                              allow_blank: true,
                              only_integer: true,
                              greater_than_or_equal_to: 0
  end
end

app/models/pafs_core/flood_protection_outcome.rb
# frozen_string_literal: true

module PafsCore
  class FloodProtectionOutcome < ApplicationRecord
    belongs_to :project

    validates_numericality_of :households_at_reduced_risk,
                              :moved_from_very_significant_and_significant_to_moderate_or_low,
                              :households_protected_from_loss_in_20_percent_most_deprived,
                              allow_blank: true,
                              only_integer: true,
                              greater_than_or_equal_to: 0
  end
end

app/models/pafs_core/funding_contributor.rb
# frozen_string_literal: true

module PafsCore
  class FundingContributor < ApplicationRecord
    belongs_to :funding_value
  end
end

app/models/pafs_core/funding_value.rb
# frozen_string_literal: true

module PafsCore
  class FundingValue < ApplicationRecord
    belongs_to :project

    has_many :funding_contributors, dependent: :destroy
    has_many :public_contributions, -> { where(contributor_type: FundingSources::PUBLIC_CONTRIBUTIONS) }, class_name: "PafsCore::FundingContributor"
    has_many :private_contributions, -> { where(contributor_type: FundingSources::PRIVATE_CONTRIBUTIONS) }, class_name: "PafsCore::FundingContributor"
    has_many :other_ea_contributions, -> { where(contributor_type: FundingSources::EA_CONTRIBUTIONS) }, class_name: "PafsCore::FundingContributor"

    validates :fcerm_gia,
              :local_levy,
              :internal_drainage_boards,
              :growth_funding,
              :not_yet_identified,
              numericality: true, allow_blank: true

    before_save :update_total

    def self.previous_years
      where(financial_year: -1)
    end

    def self.to_financial_year(year)
      where(arel_table[:financial_year].lteq(year.to_i)).order(:financial_year)
    end

    FundingSources::FUNDING_SOURCES.each do |source|
      define_method("#{source}_total") do
        return public_send(source).to_i unless FundingSources::AGGREGATE_SOURCES.include?(source)

        (public_send(source) || []).map(&:amount).compact.sum.to_i
      end
    end

    private

    def selected_funding_sources
      FundingSources::FUNDING_SOURCES.select { |s| project.public_send "#{s}?" }
    end

    def update_total
      return if destroyed?

      self.total = selected_funding_sources.map { |f| public_send("#{f}_total") }.reduce(:+) || 0
    end
  end
end

app/models/pafs_core/program_upload.rb
# frozen_string_literal: true

require "bstard"

module PafsCore
  class ProgramUpload < ApplicationRecord
    include PafsCore::FileTypes
    has_many :program_upload_items, inverse_of: :program_upload, dependent: :destroy
    has_many :program_upload_failures, through: :program_upload_items

    validate :file_selected
    validates :number_of_records, numericality: { only_integer: true }
    validates :status, inclusion: { in: %w[new uploaded processing completed failed] }

    # rubocop:disable Style/HashSyntax
    def processing_state
      machine = Bstard.define do |fsm|
        fsm.initial status
        fsm.event :upload, :new => :uploaded
        fsm.event :process, :uploaded => :processing
        fsm.event :complete, :processing => :completed
        fsm.event :error, :processing => :failed, :new => :failed
        fsm.when :any do |_event, _prev_state, new_state|
          update_attribute(:status, new_state)
        end
      end
    end
    # rubocop:enable Style/HashSyntax

    def finished_processing?
      state = processing_state
      state.completed? || state.failed?
    end

    private

    def file_selected
      errors.add(:base, "^Select the completed FCERM program (.xlsx) file") if filename.blank?
    end
  end
end

app/models/pafs_core/program_upload_failure.rb
# frozen_string_literal: true

module PafsCore
  class ProgramUploadFailure < ApplicationRecord
    belongs_to :program_upload_item, inverse_of: :program_upload_failures

    validates :field_name, presence: true
    validates :messages, presence: true
  end
end

app/models/pafs_core/program_upload_item.rb
# frozen_string_literal: true

module PafsCore
  class ProgramUploadItem < ApplicationRecord
    belongs_to :program_upload, inverse_of: :program_upload_items
    has_many :program_upload_failures, inverse_of: :program_upload_item,
                                       dependent: :destroy

    validates :reference_number, presence: true
  end
end

app/models/pafs_core/reference_counter.rb
# Play nice with Ruby 3 (and rubocop)
# frozen_string_literal: true

module PafsCore
  class ReferenceCounter < ApplicationRecord
    def self.next_sequence_for(rfcc_code)
      raise ArgumentError, "Invalid RFCC code" unless RFCC_CODES.include? rfcc_code

      counters = []
      # look up the counters for the rfcc_code
      rc = ReferenceCounter.find_by!(rfcc_code: rfcc_code)
      rc.with_lock do
        if rc.low_counter == 999
          rc.high_counter += 1
          rc.low_counter = 1
        else
          rc.low_counter += 1
        end
        counters << rc.high_counter
        counters << rc.low_counter
        rc.save!
      end

      counters
    end

    def self.seed_counters
      RFCC_CODES.each do |code|
        ReferenceCounter.find_or_create_by(rfcc_code: code)
      end
    end
  end
end

app/models/pafs_core/state.rb
# frozen_string_literal: true

module PafsCore
  class State < ApplicationRecord
    VALID_STATES = %w[draft completed submitted updatable updated archived finished].freeze

    belongs_to :project, inverse_of: :state, optional: true
    validates :state, inclusion: { in: VALID_STATES }

    def self.submitted
      where(state: "submitted")
    end

    def self.refreshable
      # states that can be "opened" during programme refresh
      where(state: %w[completed submitted updated finished])
    end
  end
end

app/models/pafs_core/user.rb
# frozen_string_literal: true

module PafsCore
  class User < ApplicationRecord
    validates :first_name, presence: true
    validates :last_name, presence: true
    # validates_uniqueness_of :email, case_sensitive: false

    has_many :user_areas
    has_many :areas, through: :user_areas

    has_many :projects, foreign_key: "creator_id"

    # possible if a user has many areas they could initiate downloads in more than
    # one area
    has_many :area_downloads, inverse_of: :user

    def self.expired_invite
      where(invitation_accepted_at: nil)
        .where(arel_table[:invitation_created_at].lt(30.days.ago))
    end

    def full_name
      "#{first_name} #{last_name}"
    end

    def rfcc_code(area_name = nil)
      area = nil
      area = if area_name
               PafsCore::Area.find_by_name(area_name)
             else
               # find the PSO area under which this user belongs
               primary_area
             end
      unless area.ea_area?
        area = area.parent if area.rma?
        PafsCore::PSO_RFCC_MAP.fetch(area.name)
      end
    end

    def primary_area
      user_areas.primary_area.first&.area
    end

    def update_primary_area(area)
      user_areas.where(primary: true).update_all(primary: false)
      user_areas.find_by(area: area).update(primary: true)
    end
  end
end

app/models/pafs_core/user_area.rb
# Play nice with Ruby 3 (and rubocop)
# frozen_string_literal: true

module PafsCore
  class UserArea < ApplicationRecord
    belongs_to :user
    belongs_to :area

    validate :area_is_set
    validates_uniqueness_of :user_id, scope: :area_id, message: "^Unable to assign area multiple times"

    default_scope { order(primary: :desc) }

    # When saving changes to the users areas, we need to be sure that we also
    # update the users updated_at timestamp so that the cache of area_ids is invalidated.
    after_commit :touch_user

    def self.primary_area
      includes(:area).where(primary: true)
    end

    private

    def touch_user
      user&.touch
    end

    def area_is_set
      # we're ignoring the user_id as that should be set when contructing
      # the user_area, it's the area that the user will be selecting.
      # Also if we validate both we'll get error messages for both when no
      # area is selected which the user cannot do anything about from the front-end
      errors.add(:area_id, "^Select an area") if area_id.nil?
    end
  end
end

app/controllers/pafs_core/application_controller.rb
# Play nice with Ruby 3 (and rubocop)
# frozen_string_literal: true

module PafsCore
  class ApplicationController < ActionController::Base
    include PafsCore::ApplicationHelper
    include PafsCore::CustomHeaders

    protect_from_forgery with: :exception

    before_action :cache_busting

    rescue_from ActionController::InvalidAuthenticityToken, with: :handle_invalid_authenticity_token

    private

    def raise_not_found
      raise ActionController::RoutingError, "Not Found"
    end

    def handle_invalid_authenticity_token(exception)
      Airbrake.notify(exception) if defined? Airbrake
      Rails.logger.error "ApplicationController authenticity failed " \
                         "(browser cookies may have been disabled): #{exception}"

      render "pafs_core/errors/invalid_authenticity_token", status: :forbidden
    end

  end
end

app/views/pafs_core/projects/_confirm_banner.html.erb
<div class="govuk-box-highlight">
  <h1 class="bold-large"><%= title %></h1>
  <% unless reference_number.nil? %>
  <p>The national project number is<br>
  <strong class="heading-medium"><%= reference_number %></strong>
  <% end %>
  </p>
</div>

app/views/pafs_core/projects/_submit_project.html.erb
<% if @project.draft? %>
  <section aria-labelledby="submission">
    <div class="grid-row submission">
      <% if can_change_project_state?(@project) %>
        <div class="column-three-quarters">
          <h2 class="heading-medium" role="heading" id="submission">
            <%= @project.summary_label(:submission_title) %>
          </h2>
        </div>
        <div class="column-two-thirds">
            <p><%= @project.summary_label(:submission_notice) %></p>
            <%= render partial: "summary/data_notice", locals: { project: @project } %>
            <% if skip_pso_confirmation? %>
              <%= link_to t("submit_project_label"),
                submit_project_path(id: @project.to_param), class: "button submit-proposal" %>
            <% else %>
              <%= link_to t("complete_project_label"),
                complete_project_path(id: @project.to_param), class: "button submit-proposal" %>
            <% end %>
        </div>
      <% else %>
        <div class="column-three-quarters">
          <h2 class="heading-medium" role="heading" id="submission">
            <p>EA Projects are now managed in PoL</p>
          </h2>
        </div>
      <% end %>
    </div>
  </section>
<% elsif pso_user? && can_change_project_state?(project) && @project.completed? %>
  <section aria-label="controls">
    <div class="grid-row">
      <div class="column-two-thirds space-kids">
        <%= link_to t("submit_project_label"),
          submit_project_path(id: @project.to_param), class: "button submit-proposal" %>
        <%= link_to t("unlock_project_label"),
          unlock_project_path(id: @project.to_param), class: "button submit-proposal" %>
      </div>
    </div>
  </section>
<% elsif pso_user? && can_revert_to_draft?(project) && @project.submitted? %>
  <section aria-label="controls">
    <div class="grid-row">
      <div class="column-two-thirds">
        <%# link_to t("unlock_project_label"),
          unlock_project_path(id: @project.to_param), class: "button submit-proposal" %>
      </div>
    </div>
  </section>
<% end %>

app/views/pafs_core/projects/confirm_archive.html.erb
<% content_for :page_title, make_page_title(t("proposal_submitted", scope: "page_titles")) %>
<div class="step-container">
  <div class="grid-row">
    <div class="column-two-thirds">
      <%= render partial: "confirm_banner", locals: { reference_number: nil, title: "Proposal has been archived" } %>
      <h2 class="heading-medium">What happens next?</h2>
      <ul class="list list-bullet">
        <li>This proposal has moved to your <%= link_to("archive", pafs_core.archives_path) %> and is no longer visible in your proposals list.</li>
        <li>Archived proposals cannot be edited or submitted.</li>
      </ul>
      <h2 class="heading-medium">If you need to change your proposal</h2>
      <ul class="list list-bullet">
        <li>Use the archive link in the banner to see your archived proposals.</li>
        <li>Return to the <%= link_to("proposal overview", project_path(@project)) %> page and click on the 'revert to draft' link.</li>
        <li>The proposal will reappear in <%= link_to("your proposals", projects_path) %> and can then be edited.</li>
      </ul>
    </div>
  </div>
</div>

app/views/pafs_core/projects/confirm_area.html.erb
<% content_for :page_title, make_page_title(t("proposal_submitted", scope: "page_titles")) %>
<div class="step-container">
  <div class="grid-row">
    <div class="column-two-thirds">
      <%= render partial: "confirm_banner",
        locals: { reference_number: @project.reference_number,
                  title: "Proposal submitted" } %>
      <h2 class="heading-medium">What happens next?</h2>
      <p>The proposal has now been marked as submitted to the Area Programming Team. They'll contact you if they need more information.</p>

      <h2 class="heading-medium">If you need to change your proposal</h2>
      <ul class="list list-bullet">
        <li>Return to the <%= link_to "proposal overview", project_path(@project) %> page and click the 'Revert to draft' button</li>
      </ul>
      <div class="form-group headroom">
        <%= link_to "Return to your proposals", projects_path, class: "button", role: "button" %>
      </div>
      <div class="form-group">
        <%= link_to "What did you think of this service?", PafsCore.configuration.complete_page_feedback_uri, target: '_blank' %> (takes 30 seconds)
      </div>
    </div>
  </div>
</div>

app/views/pafs_core/projects/confirm_pso.html.erb
<% content_for :page_title, make_page_title(t("proposal_submitted", scope: "page_titles")) %>
<div class="step-container">
  <div class="grid-row">
    <div class="column-two-thirds">
      <%= render partial: "confirm_banner",
        locals: { reference_number: @project.reference_number,
                  title: "Proposal under review" } %>

      <h2 class="heading-medium">If you need to change your proposal</h2>
      <ul class="list list-bullet">
        <li>Login to Project Online where this project can now be viewed and edited.</li>
      </ul>

      <div class="form-group headroom">
      <%= link_to "Return to your proposal overview", project_path(@project), class: "button", role: "button" %>
      </div>
    </div>
  </div>
</div>

app/views/pafs_core/projects/confirm_rma.html.erb
<% content_for :page_title, make_page_title(t("proposal_submitted", scope: "page_titles")) %>
<div class="step-container">
  <div class="grid-row">
    <div class="column-two-thirds">
      <%= render partial: "confirm_banner",
        locals: { reference_number: @project.reference_number,
                  title: "Proposal sent for review" } %>
      <h2 class="heading-medium">If you need to change your proposal</h2>
      <p>Get in touch with your local Environment Agency contact who will be able to revert your proposal back to ‘draft’ status.</p>

      <div class="form-group headroom">
      <%= link_to "Return to your proposals", projects_path, class: "button", role: "button" %>
      </div>

      <div class="form-group">
        <%= link_to "What did you think of this service?", PafsCore.configuration.complete_page_feedback_uri, target: '_blank' %> (takes 30 seconds)
      </div>
    </div>
  </div>
</div>

app/views/pafs_core/projects/index.html.erb
<% content_for :page_title, make_page_title("Your project proposals") %>
<div id="dashboard">
  <h1 class="heading-large">Your proposals</h1>

  <% if rma_user? %>
    <div class="grid-row">
      <div class="column-two-thirds">
        <div class="panel panel-indent panel-border-narrow panel-border-short">
          For submission deadlines please contact your local partnership and strategic overview officer.
        </div>
      </div>
    </div>
  <% end %>

  <div class="column-three-quarters">
    <%= form_tag(pafs_core.projects_path, method: "get", class: "search-bar") do %>
      <%= text_field_tag(:q, params[:q] || "", placeholder: "Enter a project number or name", minlength: 1, maxlength: 30, class: "form-control") %>
      <%= submit_tag("Search", class: "button button-secondary") %>
    <% end %>
  </div>

  <% if ea_user? %>
    <div class="download-all-proposals-link">
      <%= link_to t('download_all_proposals_label'), pafs_core.multi_downloads_path %>
    </div>
  <% else %>
    <% if can_create_project? %>
      <div class="create-new-project">
        <%= link_to t('create_a_new_project_label'), pafs_core.new_bootstrap_path, class: "button" %>
      </div>
    <% else %>
      <div class="column-three-quarters create-new-project">
        To create a new EA-Led proposal please <a href="https://aimspd.sharepoint.com/sites/pwa">go to AIMS\:PD</a>
        <br/>
        RMA-led projects are to be created by the RMA, by logging into PAFS.
      </div>
    <% end %>
  <% end %>

  <section>
    <% unless @projects.empty? %>
      <table class="dashboard">
        <thead>
          <tr>
            <th scope="col" class="project-number">National project number</th>
            <th scope="col" class="sortable-heading">Project name</th>
            <th scope="col">Created by</th>
            <th scope="col">
              <% sort_properties_for_col = get_next_sort_order_and_curr_arrow(project_sort_column, "updated_at", project_sort_order, "updated_at", "desc") %>

              <%= link_to "Last updated", pafs_core.projects_path(sort_col: "updated_at", sort_order: sort_properties_for_col[:next_sort_order]), class: "sortable-link" %>
              <span class="sortable-arrow"><%=h raw(sort_properties_for_col[:curr_arrow]) %></span>
            </th>

            <% unless ea_user? %>
              <th scope="col">Status</th>
            <% end %>

            <% if pso_user? %>
              <th scope="col">In current programme</th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% @projects.each do |project| %>
            <tr>
              <td><%= link_to project.reference_number, pafs_core.project_path(project), class: "project-link" %></td>
              <td><%= project.name %></td>
              <td><%= project.owner.name unless project.owner.blank? %></td>
              <td><%= l(project.updated_at) %></td>
              <% unless ea_user? %>
                <td><%= status_label_for(project.submission_state.current_state) %></td>
              <% end %>
              <% if pso_user? %>
                <td><%= project.consented? ? "Y" : "N" %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
    <div class="grid-row page-nav">
      <div class="pagination column-one-third">
        <%= page_entries_info @projects %>
      </div>
      <div class="column-two-thirds">
        <div class="pagination-area">
          <%= paginate @projects, left: 0, right: 0, window: 2 %>
          <%= link_to('Show All', pafs_core.projects_path(all: true), class: "button") %>
        </div>
      </div>
      <% if @projects.empty? %>
        <div class="column-three-quarters">
          <p>Please try</p>
          <ul class="list list-bullet">
            <li>a different search</li>
            <li>checking for spelling</li>
            <li>looking in your archive</li>
          </ul>
        </div>
      <% end %>
    </div>
  </section>
</div>

app/views/pafs_core/projects/new.html.erb
<div class="step-container">
  <div class="grid-row">
    <div class="column-two-thirds">
      <div class="step-form">
        <%= pafs_form_for @project, url: funding_projects_path, method: :post do |f| %>
          <%= f.error_header %>
          <h1 class="heading-large"><%= t(".heading", date: six_year_limit_date) %></h1>
          <%= f.hidden_field :id %>
          <fieldset class="inline">
            <legend class="visuallyhidden"><%= t(".heading", date: six_year_limit_date) %></legend>
            <%= f.radio_button_group(:fcerm_gia,
                                     [ { value: "true", options: { label: t("yes_option") } },
                                       { value: "false", options: { label: t("no_option") } }]) %>
          </fieldset>
          <div class="form-group">
            <%= f.submit t("save_and_continue_label"), class: 'button' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pafs_core/projects/pipeline.html.erb
<% content_for :page_title,
    make_page_title(t("pipeline",
                      scope: "page_titles")) %>
<div class="column-two-thirds">
  <h1 class="heading-large">This service is only available for projects that need funding before <%= six_year_limit_date %></h1>
  <p>If you'd like to submit a project that needs funding after 31 March 2021, download the <%= link_to t("fcerm_form_label"), t("fcerm_form_link"), rel: "external", target: "_blank" %>.</p>
  <p>Complete part 1 of the form and email it to your local partnership and strategic overview officer.</p>
  <p>You can submit the full application at a later date.</p>
  <p>
    <%= link_to t("back_to_start_label"), pafs_core.projects_path, class: "button", role: "button" %>
  </p>
</div>

app/views/pafs_core/projects/reference_number.html.erb
<h1 class="heading-large"><%= t('.heading') %></h1>
<p class="lede"><%= t('.lede') %></p>
<div class="panel">
  <span class="heading-large"><%= @project.reference_number %></span>
</div>
<p><%= t('.info') %></p>

<%= link_to t('continue_label'), pafs_core.project_step_path(id: @project.to_param, step: @project.step), class: "button" %>